openapi: 3.0.3
info:
servers:
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
        message:
          description: string message
          type: string
      required:
        - status
        - message