version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Documents
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DOCUMENTS_REDIS_PWD-password}
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: document_redactor
      DOCKER_INFLUXDB_INIT_BUCKET: documents_operations
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: some_token
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb:/var/lib/influxdb2:rw
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    environment:
      BASE_URL: "/api/swagger"
      URLS: "[ 
        { url: \"http://localhost:5050/api/documents/swagger/spec.yml\", name: \"Document-Service\" },
        { url: \"http://localhost:5050/api/sessions/swagger/spec.yml\", name: \"Sessions-Service\" }
        ]"
  nginx:
    image: nginx
    volumes:
      - ./configs/online_document_redactor.conf.tmpl:/etc/nginx/conf.d/online_document_redactor.conf.template
    ports:
      - "5050:8080"
    environment:
      - NGINX_PORT=8080
      - NGINX_DOCUMENT_HOST=documents-app:8080
      - NGINX_SESSIONS_HOST=sessions-app:8082
      - NGINX_SWAGGER_HOST=swagger-ui:8080
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/online_document_redactor.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
