version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Documents
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DOCUMENTS_REDIS_PWD-password}
    restart: unless-stopped