version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
#      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Documents