openapi: 3.0.8
info:
paths:
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        body:
          type: object
          $ref: "#/components/schemas/Body"
        style:
          $ref: "#/components/schemas/DocumentStyle"
      required:
        - id
        - title
        - body
        - style
    Body:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id
    DocumentStyle:
      type: object
      properties:
        id:
          type: integer
        size:
          type: object
          $ref: "./shared.yml#/components/schemas/Size"
      required:
        - id
        - size
    CreateUpdateDocumentView:
      type: object
      properties:
        title:
          type: string
          minLength: 1
        size:
          $ref: "./shared.yml#/components/schemas/Size"
      required:
        - title
        - size
      example:
        title: "new document"
        size:
          height:
            magnitude: 841.8897637795277
            unit: "PT"
          width:
            magnitude: 595.27559055118115
            unit: "PT"
    CompactDocument:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
      required:
        - id
        - title
    PaginatedDocuments:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/CompactDocument"
        cursor:
          type: string
      required:
        - items
        - cursor