openapi: 3.0.3
components:
  parameters:
    Limit:
      name: limit
      in: query
      description: "limit if equal 0 mean all elements"
      required: false
      schema:
        type: integer
        format: uint
        default: 10
    Cursor:
      name: cursor
      in: query
      description: cursor
      required: false
      schema:
        type: string