version: '3.9'
services:
  sessions-app:
    build:
      context: ${SESSIONS_SERVICE_CONTEXT_DOCUMENT-../..}
      dockerfile: sessions/build/package/Dockerfile
    environment:
      - SESSIONS_APP_PORT=${SESSIONS_APP_PORT-8082}
      - SESSIONS_DEVELOPMENT=${SESSIONS_DEVELOPMENT-true}
      - SESSIONS_DOCUMENT_AMQP_EXCHANGE_NAME=${SESSIONS_DOCUMENT_AMQP_EXCHANGE_NAME-documents-service.events}
      - SESSIONS_AMQP_URL=${SESSIONS_AMQP_URL-amqp://user:password@rabbitmq:5672/}
      - SESSIONS_DOCUMENT_REST_BASE_URL=${SESSIONS_DOCUMENT_REST_BASE_URL-http://documents-app:8080/api/documents/v1}
      - SESSIONS_INFLUXDB_URL=${SESSIONS_INFLUXDB_URL-http://influxdb:8086}
      - SESSIONS_INFLUXDB_TOKEN=${SESSIONS_INFLUXDB_TOKEN-some_token}
    ports:
      - ${SESSIONS_APP_PORT-8082}:${SESSIONS_APP_PORT-8082}
    restart: unless-stopped