openapi: 3.0.8
info:
  title: Sessions service API
  description: Service to handle sessions in documents redactor
  version: 1.0.0
paths:
  /api/sessions/v1/documents/{id}/revisionId:
    get:
      description: return current document revision id
      operationId: getDocumentRevisionId
      tags:
        - documents
      parameters:
        - $ref: "./parameters/documents.yml#/components/parameters/DocumentId"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "./schemas/documents.yml#/components/schemas/Document"
        default:
          content:
            application/json:
              schema:
                $ref: "./schemas/shared.yml#/components/schemas/Error"
  /api/sessions/v1/documents/{id}/sync:
    get:
      description: return all operation that need to apply
      operationId: syncDocumentsById
      tags:
        - documents
      parameters:
        - $ref: "./parameters/documents.yml#/components/parameters/DocumentId"
        - $ref: "./parameters/documents.yml#/components/parameters/RevisionId"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/operations.yml#/components/schemas/DocumentOperation"
        default:
          content:
            application/json:
              schema:
                $ref: "./schemas/shared.yml#/components/schemas/Error"
  /api/sessions/v1/documents/{id}/save:
    post:
      description: Push operation to document
      operationId: pushOperationToDocument
      tags:
        - documents
      parameters:
        - $ref: "./parameters/documents.yml#/components/parameters/DocumentId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/documents.yml#/components/schemas/SaveDocumentRequest"
      responses:
        '204':
          description: "Operation applyed"
        default:
          content:
            application/json:
              schema:
                type: array
                $ref: "./schemas/shared.yml#/components/schemas/Error"
  /api/sessions/v1/document/{id}/history:
    get:
      description: Get history of operations
      operationId: getDocumentHistory
      tags:
        - documents
      parameters:
        - $ref: "./parameters/documents.yml#/components/parameters/DocumentId"
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/documents.yml#/components/schemas/DocumentRevision"
        default:
          content:
            application/json:
              schema:
                type: array
                $ref: "./schemas/shared.yml#/components/schemas/Error"